### ISSUE TITLE
Getting error "zip error: Nothing to do!"

### ISSUE THREAD

**Issue by willdadrummer** [kc9wwh/logCollection#1]
I am getting the error "Script result: error reading input file

zip error: Nothing to do! (/private/tmp/GLXC02CF04LMD6R-will.daniel-2020-07-29-11-33-01.zip)
curl: (3) URL using bad/illegal format or missing URL

no element found at line 1, column 0, byte 0:" 

The URL is set correctly though. 
<img width="486" alt="Screen Shot 2020-08-03 at 3 13 34 PM" src="https://user-images.githubusercontent.com/52965466/89218370-e8c39380-d59b-11ea-8bf1-966f3295af7c.png">

**Comment by kc9wwh** [comment]
Hi @willdadrummer - 

This appears to be an already zipped file, correct?
Is it just a single file you are trying to upload?

**Comment by willdadrummer** [comment]
Thank you for getting back to me @kc9wwh 
I am trying to upload three log files. I have them listed below as I have them in Parameter 7

/private/var/log/install.log* /private/var/log/jamf.log /private/var/log/system.log*

**Comment by kc9wwh** [comment]
Hey @willdadrummer 

Could you please update `line 1` of the script to look like this: 
`#!/bin/bash +x`

The run the script again and send me a fully copy of the output by uploading it to the dropbox link below?
https://www.dropbox.com/request/VdOug1gBdjsgRvIpW7YF

**Comment by willdadrummer** [comment]
@kc9wwh I ran the script again through Jamf with the +x added to the first line, but I got the same result in Jamf. I may be misunderstanding though. Did you want me to run this locally and change the parameters in the script?

**Comment by kc9wwh** [comment]
@willdadrummer Yeah, you may have to run it locally. I was hoping the extra information would populate in the policy log, but I guess not. Please run it locally and send over the results when you have a moment.

**Comment by willdadrummer** [comment]
@kc9wwh Is there an easy way to change the parameter variables to input information locally?

**Comment by kc9wwh** [comment]
@willdadrummer - Yes, just replace `$#` with the actual variables. 

```
## User Variables
jamfProURL="https://jamfpro.acme.net:8443"
jamfProUser="api-user"
jamfProPass="superSecretPass"
logFiles="/private/var/log/jamf.log /private/var/log/system.log* /private/var/log/install.log*"
```

**Comment by willdadrummer** [comment]
Welp I will give you a good laugh. The issue was a $ in the password for the api user... Sorry to waste your time, but thank you for your help!
