### ISSUE TITLE
Adding bearer auth support

### ISSUE THREAD

**Issue by altonbrailovskiy** [kc9wwh/logCollection#25]
With the jamf API changes, this stopped working with basic auth methods. Along with jamf support, I made some tweaks and came up with an updated script that works with the new updated bearer changes required for this to work correctly. 

https://github.com/altonbrailovskiy/logCollection/blob/master/BearerAuth.sh

[BearerAuth.txt](https://github.com/kc9wwh/logCollection/files/13518366/BearerAuth.txt)

**Comment by sean-enright** [comment]
I tried your script change and its not working for me (nor is the original)
What other changes if any do i need to make?

Here is the log from an automox log i was trying to grab and upload. 

<html>
<body>

Executing Policy Collect Automox Log Files
--
Running script Collect  Logs...
Script exit code: 0
Script result: /Library/Application Support/JAMF/tmp/Collect  Logs: line 65:  : command not found/Library/Application Support/JAMF/tmp/Collect  Logs: line 66:  : command not found /Library/Application Support/JAMF/tmp/Collect  Logs: line 72:  awk: command not found   adding: var/log/amagent/amagent.log (deflated 92%)   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                  Dload  Upload   Total   Spent    Left  Speed    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100   422  100   422    0     0   3341      0 --:--:-- --:--:-- --:--:--  3349  mismatched tag at line 10, column 2, byte 404: <p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2">here</a>.<br> 	Please continue your visit at our <a href="/">home page</a>. </p> =^ </body> </html>  at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/XML/Parser.pm line 187. /Library/Application Support/JAMF/tmp/Collect  Logs: line 88:  : command not found   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                  Dload  Upload   Total   Spent    Left  Speed    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  35  357k    0     0   35  128k      0  1012k --:--:-- --:--:-- --:--:-- 1007k  35  358k  100   422   35  128k   3212   974k --:--:-- --:--:-- --:--:--  972k <html> <head> 	<title>Status page</title> </head> <body style="font-family: sans-serif;"> <p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Unauthorized</p> <p>The request requires user authentication</p> <p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2">here</a>.<br> 	Please continue your visit at our <a href="/">home page</a>. </p> </body> </html>/Library/Application Support/JAMF/tmp/Collect  Logs: line 102:  : command not found


</body>
</html>

**Comment by altonbrailovskiy** [comment]
--
Confirmed via MacAdmins that this is working after retrying. Hope this helps others!

**Comment by sean-enright** [comment]
YES, I have removed my original comment as well since the problem was me adding scripting to the script that caused it to fail. Works Great, thank you again for the assist.
