### ISSUE TITLE
Serial Number

### ISSUE THREAD

**Issue by Top-Goodman** [kc9wwh/logCollection#3]
Hello,
Using system_profiler for serial number was causing timeouts and the script was delaying a long time without running successfully.
I think this might be because of Filevault. So not sure if you want to investigate swapping out the variable all together, or maybe use a check to see if filevault is enabled, then declare the variable a different way.
I changed this to mySerial=$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}')

The script isn't working still, however the serial number is at least getting populated now.

**Comment by kc9wwh** [comment]
@Top-Goodman are you still having issues?

**Comment by Top-Goodman** [comment]
Hello, we kind of stopped using the logging when it stopped working. Thanks
for following up.

**Comment by kc9wwh** [comment]
@Top-Goodman, sorry to hear. Unfortunately I’m not able to duplicate this and others haven’t had issues either. I’ll close this out then, but if you want to relook at this let me know.

**Comment by Top-Goodman** [comment]
No worries. Thank you
