### ISSUE TITLE
Computer ID - Monterey

### ISSUE THREAD

**Issue by MichaelLambert78** [kc9wwh/logCollection#6]
Looks like the computer ID in Jamf is not getting populated properly and therefore unable to upload the files to the computer record with Monterey. Possibly xpath related.

**Comment by baberlevi** [comment]
You could test https://github.com/kc9wwh/logCollection/pull/7 and see if it works for you. Seems fine for me.

**Comment by kc9wwh** [comment]
This has been resolved in PR #7.
